spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MobileDB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8084
#Logging level: ERROR. We can add TRACE, INFO, DEBUG, WARN.
logging:
  level:
    root: ERROR
    com.example: WARN
  file:
    name: manufacture-log